### ISSUE TITLE
Crash on Conversion

### ISSUE THREAD

**Issue by casualgecko** [FamilySearch/gedcom5-conversion#8]
Running Java 7 Update 9 on Windows 7 

Pulled gedcom5-conversion-0.2.0-SNAPSHOT-full.jar

When converting my GEDCOM pulled from ancestry I get the following error:

Exception in thread "main" java.lang.NullPointerException
        at org.gedcomx.conversion.gedcom.dq55.SubmitterMapper.toContributor(Subm
itterMapper.java:34)
        at org.gedcomx.conversion.gedcom.dq55.GedcomMapper.toGedcomx(GedcomMappe
r.java:43)
        at org.gedcomx.tools.Gedcom2Gedcomx.convert55File(Gedcom2Gedcomx.java:20
6)
        at org.gedcomx.tools.Gedcom2Gedcomx.doMain(Gedcom2Gedcomx.java:159)
        at org.gedcomx.tools.Gedcom2Gedcomx.main(Gedcom2Gedcomx.java:216)

**Comment by bdefore** [comment]
I had this issue too. Apparently the submitter is a required field for some silly reason. It worked for me after adding:
```
1 SUBM Foo
```
right above the entry for GEDC

**Comment by stoicflame** [comment]
Weird. Thanks for the tip.

**Comment by Bipsy** [comment]
I just had this occur to me as well. I'll try your fix @bdefore

**Comment by Bipsy** [comment]
@bdefore yeah, adding a Submitter solved this issue. Is this a bug with the converter?

**Comment by bdefore** [comment]
@Bipsy i'd say it is a bug if a submitter is not a required field. i had a look through the GEDCOM 5.5 specifications, but unless i'm missing something it does not say that it is. see http://www.gedcomx.org/GEDCOM-5.5.1.pdf page 28 ... perhaps @casualgecko could retitle this?

**Comment by bdefore** [comment]
and if required, a helpful error message is much preferable to a null pointer exception

**Comment by bdefore** [comment]
#13 may be a duplicate of this, and based on the conversation there this may be fixed with 1.4.0

**Comment by stoicflame** [comment]
I'm pretty sure I fixed this in the latest release, version 1.4.0. 

Is that not correct?

**Comment by Bipsy** [comment]
@stoicflame I downloaded the jar file yesterday and am still getting this error.

**Comment by bdefore** [comment]
@stoicflame i no longer have steps i can reproduce to verify

**Comment by stoicflame** [comment]
@Bipsy, there's no way you're getting the same stack trace if you've downloaded the latest jar, version 1.4.0. There's no executable code at `SubmitterMapper.java:34`, see:

https://github.com/FamilySearch/gedcom5-conversion/blob/master/src/main/java/org/gedcomx/conversion/gedcom/dq55/SubmitterMapper.java#L34

So you're either getting a different error or you didn't get the latest code.

**Comment by Bipsy** [comment]
I guess I may have assumed it was the same stack trace because the adding a submitter fixes my problem, but here is the stack trace: 

```
Exception in thread "main" java.lang.NullPointerException
	at org.gedcomx.conversion.gedcom.dq55.SubmitterMapper.toContributor(SubmitterMapper.java:34)
	at org.gedcomx.conversion.gedcom.dq55.GedcomMapper.toGedcomx(GedcomMapper.java:42)
	at org.gedcomx.conversion.gedcom.dq55.GedcomMapper.toGedcomx(GedcomMapper.java:33)
	at org.gedcomx.tools.Gedcom2Gedcomx.convert55File(Gedcom2Gedcomx.java:202)
	at org.gedcomx.tools.Gedcom2Gedcomx.doMain(Gedcom2Gedcomx.java:156)
	at org.gedcomx.tools.Gedcom2Gedcomx.main(Gedcom2Gedcomx.java:222)
```

This is using the jar that I just downloaded a few minutes ago from the link in the README.

**Comment by stoicflame** [comment]
Oh, that's just an out-of-date link in the README.

Try again.

**Comment by Bipsy** [comment]
@stoicflame Thanks for updating the link and fixing the bug. Works fine now.
